-- =============================================================
-- BhumiDrishti — Batches Table
-- Tracks orthophoto batch analysis runs across building polygons
-- =============================================================

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS batches (
  id                VARCHAR(50)   PRIMARY KEY,
  -- e.g. BATCH-7234 — generated by backend

  site_name         VARCHAR(200)  NOT NULL,
  -- user-entered name like "Antakya Ward 3"

  site_id           BIGINT,
  -- references sites.id for canonical site entity

  ortho_upload_id   VARCHAR(20),
  -- references uploads.id for the post-earthquake GeoTIFF

  area_polygon      GEOMETRY(Polygon, 4326),
  -- user-drawn polygon from frontend MapboxDraw

  total_buildings   INTEGER       DEFAULT 0,
  processed         INTEGER       DEFAULT 0,
  failed            INTEGER       DEFAULT 0,
  skipped           INTEGER       DEFAULT 0,

  status            VARCHAR(20)   DEFAULT 'queued',
  -- queued | processing | complete | failed

  worker_name       VARCHAR(100),
  force_reanalyze   BOOLEAN       DEFAULT FALSE,

  created_at        TIMESTAMPTZ   DEFAULT NOW(),
  started_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_batches_status
  ON batches(status);

CREATE INDEX IF NOT EXISTS idx_batches_area
  ON batches USING GIST(area_polygon);

CREATE INDEX IF NOT EXISTS idx_batches_site_id
  ON batches(site_id);

DO $$
BEGIN
  IF to_regclass('public.sites') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM information_schema.table_constraints
       WHERE table_name = 'batches'
         AND constraint_name = 'fk_batches_site'
     ) THEN
    ALTER TABLE batches
      ADD CONSTRAINT fk_batches_site
      FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE SET NULL;
  END IF;
END $$;
