-- =============================================================
-- BhumiDrishti — Uploads Table
-- Tracks every file uploaded by field workers
-- Separate from assessments — assessments are the output,
-- uploads are the input
-- =============================================================

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS uploads CASCADE;

CREATE TABLE uploads (

  -- ── Identity ───────────────────────────────────────────────
  id                VARCHAR(20)   PRIMARY KEY,
  -- e.g. UPL-4821 — generated by backend on upload

  -- ── File info ──────────────────────────────────────────────
  original_filename VARCHAR(500)  NOT NULL,
  -- original name of file as uploaded by user
  -- e.g. "collapsed_building_hatay_01.jpg"

  saved_path        VARCHAR(500)  NOT NULL,
  -- relative path where file is saved on disk
  -- e.g. "uploads/photos/upl_4821_photo.jpg"

  file_type         VARCHAR(20)   NOT NULL,
  -- ground_photo | drone_image | drone_orthophoto | video | video_frame

  mime_type         VARCHAR(100),
  -- e.g. "image/jpeg" | "video/mp4" | "image/tiff"

  file_size_bytes   BIGINT,
  -- file size in bytes

  -- ── Location ───────────────────────────────────────────────
  lat               FLOAT,
  -- GPS latitude at time of upload
  -- from device GPS or image EXIF

  lon               FLOAT,
  -- GPS longitude at time of upload

  geom              GEOMETRY(Point, 4326),
  -- auto-derived from lat/lon by trigger

  location_source   VARCHAR(20)   DEFAULT 'device_gps',
  -- device_gps | exif | manual | unknown
  -- where the GPS coordinates came from

  gps_accuracy_m    FLOAT,
  -- GPS accuracy in metres if available from device

  -- ── Processing status ──────────────────────────────────────
  status            VARCHAR(20)   NOT NULL DEFAULT 'uploaded',
  -- uploaded    → file saved to disk, not yet processed
  -- queued      → added to processing queue
  -- processing  → Gemma 4 currently analyzing
  -- done        → analysis complete, assessment created
  -- failed      → processing failed, see error_message
  -- skipped     → deliberately skipped (e.g. duplicate)

  is_analyzed       BOOLEAN       NOT NULL DEFAULT FALSE,
  -- simple flag — true when status = done
  -- used for quick queries without joining assessments

  -- ── Video specific ─────────────────────────────────────────
  duration_seconds  FLOAT,
  -- video duration in seconds, null for non-video files

  frames_extracted  INTEGER,
  -- number of frames extracted from video by FFmpeg
  -- null for non-video files

  -- ── Orthophoto specific ────────────────────────────────────
  is_georeferenced  BOOLEAN       DEFAULT FALSE,
  -- true if file has valid CRS and coordinates
  -- always true for GeoTIFF orthophotos

  cog_path          VARCHAR(500),
  -- path to COG converted version of GeoTIFF
  -- null until COG conversion is complete
  -- e.g. "uploads/orthophotos/upl_4821_cog.tif"

  bounds_west       FLOAT,
  bounds_south      FLOAT,
  bounds_east       FLOAT,
  bounds_north      FLOAT,
  -- bounding box of orthophoto in WGS84
  -- extracted from GeoTIFF metadata on upload
  -- used to know which buildings to process

  -- ── Relationships ──────────────────────────────────────────
  assessment_id     VARCHAR(20),
  -- ID of the assessment created from this upload
  -- null until processing is complete
  -- references assessments(id)

  batch_id          VARCHAR(50),
  -- for orthophoto uploads that spawn batch processing
  -- all building chips from same orthophoto share batch_id
  -- null for ground photo and video uploads

  parent_upload_id  VARCHAR(20),
  -- for video frames extracted from a video
  -- points to the parent video upload record
  -- null for non-derived files

  -- ── Error handling ─────────────────────────────────────────
  error_message     TEXT,
  -- error details if status = failed
  -- e.g. "FFmpeg extraction failed: codec not supported"

  retry_count       INTEGER       DEFAULT 0,
  -- how many times processing was retried

  -- ── Field worker ───────────────────────────────────────────
  worker_name       VARCHAR(100),
  -- name of field worker who uploaded this file

  field_note        TEXT,
  -- optional note attached at upload time
  -- passed to Gemma 4 as context

  -- ── Timestamps ─────────────────────────────────────────────
  uploaded_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  -- when file arrived at server

  processing_started_at TIMESTAMPTZ,
  -- when Gemma 4 started analyzing

  processing_done_at    TIMESTAMPTZ,
  -- when analysis completed

  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()

);

-- =============================================================
-- INDEXES
-- =============================================================

CREATE INDEX idx_uploads_geom
  ON uploads USING GIST(geom)
  WHERE geom IS NOT NULL;

CREATE INDEX idx_uploads_status
  ON uploads(status);

CREATE INDEX idx_uploads_is_analyzed
  ON uploads(is_analyzed);

CREATE INDEX idx_uploads_file_type
  ON uploads(file_type);

CREATE INDEX idx_uploads_assessment_id
  ON uploads(assessment_id)
  WHERE assessment_id IS NOT NULL;

CREATE INDEX idx_uploads_batch_id
  ON uploads(batch_id)
  WHERE batch_id IS NOT NULL;

CREATE INDEX idx_uploads_parent_upload_id
  ON uploads(parent_upload_id)
  WHERE parent_upload_id IS NOT NULL;

CREATE INDEX idx_uploads_worker
  ON uploads(worker_name);

CREATE INDEX idx_uploads_uploaded_at
  ON uploads(uploaded_at DESC);

-- =============================================================
-- TRIGGER — auto update geom and updated_at
-- =============================================================
CREATE OR REPLACE FUNCTION update_upload_geom()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.lat IS NOT NULL AND NEW.lon IS NOT NULL THEN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.lon, NEW.lat), 4326);
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_upload_geom
  BEFORE INSERT OR UPDATE ON uploads
  FOR EACH ROW
  EXECUTE FUNCTION update_upload_geom();

-- =============================================================
-- VERIFY
-- =============================================================
SELECT
  column_name,
  data_type,
  column_default,
  is_nullable
FROM information_schema.columns
WHERE table_name = 'uploads'
  AND table_schema = 'public'
ORDER BY ordinal_position;
