-- =============================================================
-- BhumiDrishti — Assessments Table
-- Complete schema with all fields needed by the application
-- Run this in PostGIS after load_gis_data.sh
-- =============================================================

-- Enable PostGIS if not already enabled
CREATE EXTENSION IF NOT EXISTS postgis;

-- Drop existing table for clean creation
DROP TABLE IF EXISTS assessments CASCADE;

-- =============================================================
-- MAIN ASSESSMENTS TABLE
-- =============================================================
CREATE TABLE assessments (

  -- ── Identity ───────────────────────────────────────────────
  id                    VARCHAR(20)   PRIMARY KEY,
  -- e.g. ASS-2847 — generated by backend at creation time

  -- ── Location ───────────────────────────────────────────────
  lat                   FLOAT         NOT NULL,
  lon                   FLOAT         NOT NULL,
  geom                  GEOMETRY(Geometry, 4326),
  -- geom is auto-derived from lat/lon, used for spatial queries

  -- ── Administrative location ────────────────────────────────
  province              VARCHAR(100),
  -- Hatay or Adiyaman — from PostGIS reverse geocode
  district              VARCHAR(100),
  -- district name from turkey_districts_pts
  address_note          TEXT,
  -- optional free text address from field worker

  -- ── Input type ─────────────────────────────────────────────
  input_type            VARCHAR(20)   NOT NULL DEFAULT 'ground_photo',
  -- values: ground_photo | drone_images | orthophoto | satellite | video

  -- ── File paths ─────────────────────────────────────────────
  photo_path            VARCHAR(500),
  -- always populated — shown in map popup
  -- ground_photo: uploaded JPEG
  -- drone_images: best selected frame JPEG
  -- orthophoto:   building chip JPEG with footprint overlay
  -- video:        best extracted frame JPEG
  -- satellite:    relevant image region JPEG

  video_path            VARCHAR(500),
  -- original video file path (only for video input)

  ortho_path            VARCHAR(500),
  -- original uploaded GeoTIFF path (only for orthophoto/satellite)
  -- used by titiler to serve raster overlay on map

  chip_path             VARCHAR(500),
  -- building-aligned chip JPEG (only for orthophoto)
  -- same as photo_path for orthophoto type

  drone_frames          JSONB         DEFAULT '[]',
  -- array of frame paths analyzed (only for drone input)
  -- e.g. ["uploads/drone/ass_2848_frame1.jpg", ...]

  -- ── Damage assessment — from Gemma 4 ───────────────────────
  severity              INTEGER       CHECK (severity BETWEEN 1 AND 5),
  -- 1=minor, 2=low, 3=moderate, 4=critical, 5=extreme

  damage_type           VARCHAR(100),
  -- e.g. full_collapse, partial_collapse, facade_damage,
  --      structural_crack, roof_damage, no_visible_damage

  damage_description    TEXT,
  -- Gemma 4 free text description of visible damage

  structural_risk       VARCHAR(50),
  -- high | moderate | low | unknown

  -- ── Building information ────────────────────────────────────
  building_type         VARCHAR(100),
  -- from OSM turkey_buildings or estimated by Gemma 4
  -- e.g. residential, commercial, school, hospital, mosque

  building_floors       VARCHAR(20),
  -- number of floors — from OSM if available, else Gemma 4 estimate
  -- stored as VARCHAR because OSM data is often inconsistent

  building_material     VARCHAR(100),
  -- stone_masonry | reinforced_concrete | brick | timber | unknown
  -- usually estimated by Gemma 4 from image

  osm_building_id       BIGINT,
  -- osm_id from turkey_buildings if building footprint was matched

  -- ── Occupant estimate ──────────────────────────────────────
  estimated_occupants   VARCHAR(20),
  -- e.g. "6-8" or "~10" or "unknown"
  -- Gemma 4 estimates based on building size and type

  occupant_status       VARCHAR(50),
  -- trapped | evacuated | unknown | none_present

  -- ── Recommended action ─────────────────────────────────────
  recommended_action    VARCHAR(200),
  -- e.g. immediate_search_rescue | evacuate | monitor |
  --      structural_assessment | no_action_needed

  action_priority       INTEGER       CHECK (action_priority BETWEEN 1 AND 5),
  -- 1=lowest priority, 5=highest — used for triage list ordering

  -- ── Spatial context — from PostGIS queries ─────────────────
  flood_zone            BOOLEAN       DEFAULT FALSE,
  flood_return_period   VARCHAR(20),
  -- e.g. "100yr" | "50yr" | "none"

  elevation_m           FLOAT,
  -- metres above sea level from GLO-30 DEM

  slope_degrees         FLOAT,
  -- terrain slope in degrees from DEM

  slope_risk            VARCHAR(20),
  -- high | moderate | low

  nearest_shelter       VARCHAR(200),
  -- name of nearest shelter from turkey_points
  -- e.g. "Antakya Lisesi"

  shelter_distance_m    FLOAT,
  -- distance to nearest shelter in metres

  shelter_type          VARCHAR(50),
  -- school | hospital | community_centre | mosque

  road_access           VARCHAR(20),
  -- passable | blocked | unknown

  nearest_road          VARCHAR(200),
  -- name of nearest road from turkey_lines
  -- e.g. "Atatürk Caddesi"

  road_distance_m       FLOAT,
  -- distance to nearest road in metres

  -- ── AI reasoning and output ─────────────────────────────────
  reasoning             TEXT,
  -- Gemma 4 explanation of why this severity was assigned
  -- shown in full report under "Gemma 4 reasoning"

  warnings              JSONB         DEFAULT '[]',
  -- array of warning strings
  -- e.g. ["secondary_collapse_risk", "flood_zone", "slope_instability"]

  confidence            FLOAT         CHECK (confidence BETWEEN 0 AND 1),
  -- Gemma 4 confidence score 0.0 to 1.0
  -- orthophoto assessments typically lower than ground photo

  turkish_summary       TEXT,
  -- Gemma 4 output in Turkish for field workers

  model_used            VARCHAR(50)   DEFAULT 'gemma4:26b',
  -- which model version generated this assessment

  inference_seconds     FLOAT,
  -- how long Gemma 4 took to process in seconds

  -- ── Field worker info ───────────────────────────────────────
  worker_name           VARCHAR(100),
  -- name entered by field worker at app start

  worker_device         VARCHAR(100),
  -- device identifier for tracking which device submitted

  field_note            TEXT,
  -- optional free text note from field worker
  -- e.g. "heard voices inside, road blocked from north"

  -- ── Orthophoto batch info ───────────────────────────────────
  site_id               BIGINT,
  -- canonical site id from sites table when this assessment belongs to a site workflow

  batch_id              VARCHAR(50),
  -- populated when assessment is part of orthophoto batch analysis
  -- all assessments from same orthophoto share same batch_id

  batch_building_count  INTEGER,
  -- total buildings analyzed in this batch (only on first record)

  -- ── Status and workflow ─────────────────────────────────────
  status                VARCHAR(20)   NOT NULL DEFAULT 'pending',
  -- pending | in_review | responded | closed | false_positive

  verified_by_ground    BOOLEAN       DEFAULT FALSE,
  -- TRUE if an orthophoto assessment was later confirmed by field worker

  response_team         VARCHAR(100),
  -- name of rescue team dispatched to this building

  response_notes        TEXT,
  -- coordinator notes about the response

  -- ── Timestamps ─────────────────────────────────────────────
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  responded_at          TIMESTAMPTZ
  -- when status changed to responded

);

-- =============================================================
-- INDEXES
-- =============================================================

-- Spatial index — most important, powers all map queries
CREATE INDEX idx_assessments_geom
  ON assessments USING GIST(geom);

-- Severity — triage list ordering
CREATE INDEX idx_assessments_severity
  ON assessments(severity DESC);

-- Status — filter pending/responded
CREATE INDEX idx_assessments_status
  ON assessments(status);

-- Province — filter by region
CREATE INDEX idx_assessments_province
  ON assessments(province);

-- Input type — filter by ground/drone/orthophoto
CREATE INDEX idx_assessments_input_type
  ON assessments(input_type);

-- Created at — timeline queries
CREATE INDEX idx_assessments_created_at
  ON assessments(created_at DESC);

-- Worker name — per-worker stats
CREATE INDEX idx_assessments_worker
  ON assessments(worker_name);

-- Batch id — orthophoto batch queries
CREATE INDEX idx_assessments_batch
  ON assessments(batch_id)
  WHERE batch_id IS NOT NULL;

-- Site id — site-centric filtering
CREATE INDEX idx_assessments_site_id
  ON assessments(site_id)
  WHERE site_id IS NOT NULL;

-- OSM building id — link back to building footprint
CREATE INDEX idx_assessments_osm_building
  ON assessments(osm_building_id)
  WHERE osm_building_id IS NOT NULL;

-- Composite — triage list (severity + status + province)
CREATE INDEX idx_assessments_triage
  ON assessments(province, status, severity DESC);

-- =============================================================
-- TRIGGER — auto update geom from lat/lon
-- =============================================================
CREATE OR REPLACE FUNCTION update_assessment_geom()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.geom IS NULL AND NEW.lat IS NOT NULL AND NEW.lon IS NOT NULL THEN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.lon, NEW.lat), 4326);
  ELSIF NEW.geom IS NOT NULL AND ST_SRID(NEW.geom) = 0 THEN
    NEW.geom = ST_SetSRID(NEW.geom, 4326);
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_assessment_geom
  BEFORE INSERT OR UPDATE ON assessments
  FOR EACH ROW
  EXECUTE FUNCTION update_assessment_geom();

DO $$
BEGIN
  IF to_regclass('public.sites') IS NOT NULL THEN
    ALTER TABLE assessments
      ADD CONSTRAINT fk_assessments_site
      FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE SET NULL;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

-- =============================================================
-- VERIFY
-- =============================================================
SELECT
  column_name,
  data_type,
  column_default,
  is_nullable
FROM information_schema.columns
WHERE table_name = 'assessments'
  AND table_schema = 'public'
ORDER BY ordinal_position;
